version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: sistema_hotel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mth1001939274.
      MYSQL_DATABASE: hotel_db
      MYSQL_USER: usuario_hotel
      MYSQL_PASSWORD: Sistemahotel2026.
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
